### ISSUE TITLE
Checklist 1

### ISSUE THREAD

**Issue by mtaromi** [mtaromi/tmuk14-demo#13]
Create a project hosted on GitHub with a markdown file
with a draft of a project plan.

Checklist:

- [x] Group of five students organized and recorded on Canvas.
- [x] Git: `name` and `email` set in `.gitconfig` properly for all 5 students.
- [x] Git: changes tracked through `git`.
- [ ] `README.md` with a project description.
- [ ] GitHub: project hosted on GitHub.
- [ ] GitHub: GitHub repository shared with Masoumeh ([`mtaromi`]). 
- [ ] GitHub: GitHub repository link sent to Masoumeh by email or Canvas.
- [ ] `README.md` with a table/list of the 5 group members and their GitHub handles
- [ ] `README.md`: Declaration section built with an associated commit from each of the students. (See below)
- [ ] `README.md`: proper markdown with headings / etc. 
- [ ] `README.md` with plan: What will you implement? How will it work? What kind of features will it have?
- [ ] `README.md` with plan: which language(s) will you use?
- [ ] `README.md` with plan: what build system will you use?
- [ ] Git: at least one commit from each student in the group.
- [ ] no force pushes to master/main (if you need to undo changes, use a new commit).
